# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pure Olive Oil
email: info@masetaires.com 
description: > # this means to ignore newlines until "baseurl:"
  Pure Olive Oir is a business dedicated to the exportation of high quality  
  food oils.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lorenlk.github.io" # the base hostname & protocol for your site
twitter_username: lorenlk
github_username:  lorenlk

# Build settings
markdown: kramdown
